
title: "Project Name - Long version"
short_title: "Project"
subtitle: "Here you can put some general information regarding the project."

pages:

  Test Notebook:
    notebook: "prova.ipynb"
    description: "This is a test notebook."
